### ISSUE TITLE
KotlinGradleSubplugin is deprecated in 1.4.0

### ISSUE THREAD

**Issue by rjaros** [Foso/MpApt#21]
Is there any example of how to replace `KotlinGradleSubplugin` class with `KotlinCompilerPluginSupportPlugin` as suggested by the deprecation info?

**Comment by Foso** [comment]
Hi @rjaros , yes, you can see an example here : https://github.com/Foso/MpApt/blob/master/buildSrc/src/main/kotlin/de/jensklingenberg/mpapt/MpAptGradleSubPlugin.kt

**Comment by rjaros** [comment]
Great! Thank you.
