### ISSUE TITLE
Compilation faillure on classes without properties

### ISSUE THREAD

**Issue by ATizik** [Foso/MpApt#5]
If you have an annotation on a class or constructor of a class that doesn't have any properties declared inside it's body, method `SyntheticResolveExtensionImpl.generateSyntheticProperties` fails on this line, because `getProperties` returns an empty collection:
`val isLastProperty = ((thisDescriptor.source as KotlinSourceElement).psi as KtClass).getProperties().last().equals(name)`

**Comment by Foso** [comment]
Hi @ATizik thank you for reporting this, this is already removed on the latest master branch
